import { cn } from "@/lib/utils"

/** Public path of the in-app Hubble mark. Generated by scripts/build-brand-assets.mjs. */
export const BRAND_MARK_SRC = "/brand/hubble-mark.png"

/**
 * The Hubble brand mark — the supplied logo on its own dark tile, the same
 * artwork as the favicon, the extension toolbar icon and the desktop app
 * icon (all generated from brand/hubble-logo-source.webp). It is a bitmap on
 * purpose: the logo's shaded faces are part of the design, so it is not
 * recoloured to follow the theme.
 */
export function BrandMark({ className }: { className?: string }) {
  return (
    // A plain <img>: the static desktop export has no image optimizer, and
    // this 128px asset is already sized for the UI.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={BRAND_MARK_SRC}
      alt=""
      aria-hidden="true"
      width={128}
      height={128}
      draggable={false}
      className={cn("size-5 shrink-0 select-none rounded-[22%]", className)}
    />
  )
}
