// Guards the Hubble brand across all three surfaces: every logo asset the
// web app, the extension and the desktop app ship must exist at the size its
// platform expects (they are generated by build-brand-assets.mjs from
// brand/hubble-logo-source.webp), the product metadata must say Hubble, and
// the pre-rebrand product name must not creep back into shipped source.
// Compatibility identifiers that still contain `tabdump` are listed in
// brand/README.md and are deliberately not flagged here.
import { describe, expect, it } from "vitest";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const read = (...p) => readFileSync(path.join(ROOT, ...p));
const readText = (...p) => readFileSync(path.join(ROOT, ...p), "utf8");

const PNG_SIGNATURE = "89504e470d0a1a0a";

/** Width and height from a PNG's IHDR chunk. */
function pngSize(buffer) {
  expect(buffer.subarray(0, 8).toString("hex")).toBe(PNG_SIGNATURE);
  return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
}

describe("Hubble logo assets", () => {
  it("keeps the supplied logo as the single committed source", () => {
    const source = read("brand", "hubble-logo-source.webp");
    expect(source.subarray(0, 4).toString("ascii")).toBe("RIFF");
    expect(source.subarray(8, 12).toString("ascii")).toBe("WEBP");
  });

  it.each([
    [["src", "app", "icon.png"], 512],
    [["src", "app", "apple-icon.png"], 180],
    [["public", "brand", "hubble-mark.png"], 128],
    [["extension", "icons", "icon16.png"], 16],
    [["extension", "icons", "icon32.png"], 32],
    [["extension", "icons", "icon48.png"], 48],
    [["extension", "icons", "icon128.png"], 128],
    [["src-tauri", "icons", "32x32.png"], 32],
    [["src-tauri", "icons", "128x128.png"], 128],
    [["src-tauri", "icons", "128x128@2x.png"], 256],
    [["src-tauri", "icons", "icon.png"], 512], // `tauri icon` rewrites the 1024px master at 512
  ])("%j is a square %ipx PNG", (segments, size) => {
    expect(pngSize(read(...segments))).toEqual({ width: size, height: size });
  });

  it("ships a 1200×630 Open Graph image", () => {
    expect(pngSize(read("src", "app", "opengraph-image.png"))).toEqual({ width: 1200, height: 630 });
  });

  it("ships a favicon.ico with 16, 32 and 48px PNG frames", () => {
    const ico = read("src", "app", "favicon.ico");
    expect(ico.readUInt16LE(2)).toBe(1);
    const count = ico.readUInt16LE(4);
    const sizes = [];
    for (let i = 0; i < count; i++) {
      const entry = 6 + i * 16;
      const offset = ico.readUInt32LE(entry + 12);
      const length = ico.readUInt32LE(entry + 8);
      const frame = pngSize(ico.subarray(offset, offset + length));
      expect(frame.width).toBe(ico.readUInt8(entry));
      sizes.push(frame.width);
    }
    expect(sizes).toEqual([16, 32, 48]);
  });

  it("ships the desktop platform containers", () => {
    expect(statSync(path.join(ROOT, "src-tauri", "icons", "icon.ico")).size).toBeGreaterThan(0);
    expect(statSync(path.join(ROOT, "src-tauri", "icons", "icon.icns")).size).toBeGreaterThan(0);
  });

  it("no longer ships the pre-rebrand folder glyph", () => {
    expect(existsSync(path.join(ROOT, "src", "app", "icon.svg"))).toBe(false);
    const folderPath = "M20 20a2 2 0 0 0 2-2V8";
    for (const file of [
      ["src", "components", "brand-mark.tsx"],
      ["src", "components", "marketing", "site.tsx"],
      ["extension", "popup", "popup.html"],
    ]) {
      expect(readText(...file)).not.toContain(folderPath);
    }
  });
});

describe("Hubble product metadata", () => {
  it("names the extension Hubble and points it at the generated icons", () => {
    const manifest = JSON.parse(readText("extension", "manifest.json"));
    expect(manifest.name).toBe("Hubble");
    expect(manifest.description).toContain("Hubble");
    expect(manifest.action.default_title).toContain("Hubble");
    for (const icons of [manifest.icons, manifest.action.default_icon]) {
      for (const [size, file] of Object.entries(icons)) {
        expect(pngSize(read("extension", file)).width).toBe(Number(size));
      }
    }
  });

  it("shows the Hubble mark and name in the extension popup", () => {
    const popup = readText("extension", "popup", "popup.html");
    expect(popup).toContain("<title>Hubble</title>");
    expect(popup).toMatch(/<img class="popup__brand-mark" src="\.\.\/icons\/icon\d+\.png"/);
  });

  it("brands the desktop app Hubble without changing its data identity", () => {
    const conf = JSON.parse(readText("src-tauri", "tauri.conf.json"));
    expect(conf.productName).toBe("Hubble");
    expect(conf.mainBinaryName).toBe("Hubble");
    expect(conf.bundle.publisher).toBe("Hubble");
    expect(conf.bundle.longDescription).toContain("Hubble");
    // WebView2 keys the profile that holds desktop workspaces on this
    // identifier; changing it would strand every existing user's data.
    expect(conf.identifier).toBe("app.tabdump.desktop");
    // Tauri derives the MSI upgrade code from productName unless pinned;
    // this is the value TabDump installers shipped with.
    expect(conf.bundle.windows.wix.upgradeCode).toBe("778d87a8-77ea-516f-b314-46696aa85a7c");
    for (const icon of conf.bundle.icon) {
      expect(existsSync(path.join(ROOT, "src-tauri", icon))).toBe(true);
    }
    expect(readText("src-tauri", "src", "lib.rs")).toContain('.title("Hubble")');
  });

  it("titles the web app Hubble", () => {
    expect(readText("src", "app", "layout.tsx")).toMatch(/title: "Hubble",/);
    expect(readText("src", "app", "welcome", "page.tsx")).toMatch(/siteName: "Hubble"/);
  });

  it("publishes the Hubble contact address on the legal pages", () => {
    const legal = readText("src", "components", "legal", "legal-page.tsx");
    expect(legal).toContain('const CONTACT_EMAIL = "hubbleai.team@gmail.com"');
    expect(legal).not.toContain("tabdump.team@gmail.com");
  });
});

describe("no pre-rebrand product name in shipped source", () => {
  const SHIPPED = ["src", "extension", "src-tauri/src", "src-tauri/tauri.conf.json", "src-tauri/capabilities", "public"];
  const TEXT = /\.(tsx?|jsx?|mjs|css|html|json|rs|sql|svg|txt)$/;

  function* files(entry) {
    const full = path.join(ROOT, entry);
    if (!existsSync(full)) return;
    if (statSync(full).isFile()) {
      yield entry;
      return;
    }
    for (const name of readdirSync(full)) {
      if (name === "node_modules" || name === "target") continue;
      yield* files(path.join(entry, name));
    }
  }

  it("never says TabDump outside tests", () => {
    const offenders = [];
    for (const root of SHIPPED) {
      for (const file of files(root)) {
        if (!TEXT.test(file) || /\.test\.|__fixtures__|__seed__/.test(file)) continue;
        const text = readText(file);
        // Branding forms only. Lowercase `tabdump` and `TABDUMP_` are the
        // compatibility identifiers documented in brand/README.md.
        for (const match of text.matchAll(/TabDump|Tab Dump|(?<![_A-Z])TABDUMP(?![_A-Z])/g)) {
          offenders.push(`${file}: ${match[0]}`);
        }
      }
    }
    expect(offenders).toEqual([]);
  });
});
